# Generated by Django 2.2.7 on 2019-11-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('High', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shares_Traded', models.IntegerField(blank=True)),
                ('Turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
